image: node:9-alpine

stages:
- build
- test
- deploy

build site:
  stage: build
  script:
    - npm install
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules
  artifacts:
    paths:
      - node_modules

test site:
  stage: test
  dependencies:
    - build site
  script:
    - npm test
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
    - content
    - src
    - build
    when: on_failure

# Deploy jobs
deploy staging:
  stage: deploy
  only:
    - staging@monax/docs.agreements.network
  before_script:
    - apk add --no-cache --update git openssh-client
    - |
      eval $(ssh-agent -s) && \
      echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null && \
      mkdir -p $HOME/.ssh && chmod 700 $HOME/.ssh && \
      echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config && \
      git config --global user.name "Billings, a Bot" && \
      git config --global user.email "billings@monax.io" && \
      git clone git@github.com:agreements-network/docs build
  script:
    - |
      npm run-script build
      cd build
      git add -A :/
      git commit -m "Automatic document generation: $CI_COMMIT_SHA"
      git push origin master
