version: 2

jobs:
  build:
    docker:
      - image: node:9-alpine
    steps:
      - checkout
      - run:
          name: "NPM Install"
          command: npm install
      - run:
          name: "NPM Test"
          command: npm test
      - add_ssh_keys
      - run:
          name: "Merge to Master"
          command: |
            apk add --no-cache --update git openssh-client
            mkdir -p $HOME/.ssh && chmod 700 $HOME/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > $HOME/.ssh/config
            git config --global user.name "Billings, a Bot"
            git config --global user.email "billings@monax.io"
            git clone git@github.com:agreements-network/docs build
            npm run-script build
            cd build
            git add -A :/
            git commit -m "Automatic document generation: $CIRCLE_SHA1" || true
            git push origin master

